export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_SUNRISE_SUNSET_RESULTS = 'ADD_SUNRISE_SUNSET_RESULTS'

export const FETCH_LOCATION_REQUEST = 'FETCH_LOCATION_REQUEST'
export const FETCH_LOCATION_FAILURE = 'FETCH_LOCATION_FAILURE'
export const FETCH_LOCATION_SUCCESS = 'FETCH_LOCATION_SUCCESS'

export const FETCH_SUNRISE_SUNSET_REQUEST = 'FETCH_SUNRISE_SUNSET_REQUEST'
export const FETCH_SUNRISE_SUNSET_FAILURE = 'FETCH_SUNRISE_SUNSET_FAILURE'
export const FETCH_SUNRISE_SUNSET_SUCCESS = 'FETCH_SUNRISE_SUNSET_SUCCESS'

export default { ADD_LOCATION, ADD_SUNRISE_SUNSET_RESULTS }
