// Location
export const GET_LOCATION = 'GET_LOCATION'

// Breakpoints
export const GET_BREAKPOINTS = 'GET_BREAKPOINTS'
export const UPDATE_AM_BREAKPOINTS = 'UPDATE_AM_BREAKPOINTS'

// Current Index
export const GET_CURRENT_INDEX = 'GET_CURRENT_INDEX'
export const INC_CURRENT_INDEX = 'INC_CURRENT_INDEX'

// Remaining
export const GET_REMAINING = 'GET_REMAINING'

// Target
export const GET_TARGET = 'GET_TARGET'

// Status
export const GET_BREAKPOINTS_REQUEST = 'GET_BREAKPOINTS_REQUEST'
export const GET_BREAKPOINTS_FAIL = 'GET_BREAKPOINTS_REQUEST'
export const GET_BREAKPOINTS_SUCCESS = 'GET_BREAKPOINTS_SUCCESS'

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST'
export const GET_LOCATION_FAIL = 'GET_LOCATION_FAIL'
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS'

export const statuses = {
  GET_BREAKPOINTS_REQUEST,
  GET_BREAKPOINTS_SUCCESS,
  GET_BREAKPOINTS_FAIL,
  GET_LOCATION_REQUEST,
  GET_LOCATION_SUCCESS,
  GET_LOCATION_FAIL
}
