export const GET_TIME_LEFT = 'GET_TIME_LEFT'
export const GET_TIME_LEFT_FAILURE = 'GET_TIME_LEFT_FAILURE'
export const UPDATE_TIME_LEFT_AFTER_SUNSET = 'UPDATE_TIME_LEFT_AFTER_SUNSET'

export const FETCH_SUNRISE_SUNSET_REQUEST = 'FETCH_SUNRISE_SUNSET_REQUEST'
export const FETCH_SUNRISE_SUNSET_FAILURE = 'FETCH_SUNRISE_SUNSET_FAILURE'
export const FETCH_SUNRISE_SUNSET_SUCCESS = 'FETCH_SUNRISE_SUNSET_SUCCESS'

export const INC_NOW = 'INC_NOW'
